version: "3.9"

services:
  site:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "4500:80"
    volumes:
      - /data/php/:/app
    networks:
      - rede-site-php
 
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes: 
      - /data/mysql-data:/var/lib/mysql
    networks:
      - rede-site-php

  php-myadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
    ports:
      - "8080:80"
    volumes:
      - /data/php/admin/uploads.ini:/usr/local/etc/php/conf.d/phpmyadmin.ini
    networks:
      - rede-site-php

networks:
  rede-site-php:
    driver: bridge
